package App;
import BO.ComandasBO;
import Model.Comandas;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class ComandasF extends javax.swing.JInternalFrame {
    public ComandasF() {
        initComponents();
        inicializarComboPagamento();
        atualizarListagemComandas();
    }
    
    private void inicializarComboPagamento() {
        FPagamento.removeAllItems();
        FPagamento.addItem("Dinheiro");
        FPagamento.addItem("Cartão");
        FPagamento.addItem("Pix");
        FPagamento.setSelectedIndex(0);
    }
    
    private void atualizarListagemComandas() {
        try {
            ComandasBO bo = new ComandasBO();
            List<Comandas> todas = bo.listarTodas();
            txtAreaComandas.setText("");
            if (todas == null || todas.isEmpty()) {
                txtAreaComandas.setText("Nenhuma comanda cadastrada.");
                return;
            }
            for (Comandas c : todas) {
                String status = c.isStatus() ? "Aberta" : "Fechada";
                String dataAbertura = c.getDataAbertura() != null ? c.getDataAbertura().toString() : "-";
                String dataFechamento = c.getDataFechamento() != null ? c.getDataFechamento().toString() : "-";
                txtAreaComandas.append(
                        "ID: " + c.getId() +
                        " | Mesa: " + c.getMesa() +
                        " | Cliente: " + c.getNomePessoa() +
                        " | Garçom: " + c.getNomeGarcom() +
                        " | Status: " + status +
                        " | Abertura: " + dataAbertura +
                        " | Fechamento: " + dataFechamento +
                        "\n"
                );
            }
        } catch (Exception e) {
            txtAreaComandas.setText("Erro ao atualizar listagem: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbrirComanda = new javax.swing.JButton();
        EditarComanda = new javax.swing.JButton();
        RemoverComanda = new javax.swing.JButton();
        ListarComandas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMesa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdGarcom = new javax.swing.JTextField();
        txtGarcom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaComandas = new javax.swing.JTextArea();
        FecharComanda = new javax.swing.JButton();
        FecharMenu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdComanda = new javax.swing.JTextField();
        FPagamento = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Comandas");

        AbrirComanda.setText("Abrir comanda");
        AbrirComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirComandaActionPerformed(evt);
            }
        });

        EditarComanda.setText("Editar comanda");
        EditarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarComandaActionPerformed(evt);
            }
        });

        RemoverComanda.setText("Remover comanda");
        RemoverComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverComandaActionPerformed(evt);
            }
        });

        ListarComandas.setText("Listar fechadas");
        ListarComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarComandasActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente:");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Número da mesa:");

        txtMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesaActionPerformed(evt);
            }
        });

        jLabel4.setText("ID do garçom:");

        jLabel5.setText("Garçom:");

        txtIdGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdGarcomActionPerformed(evt);
            }
        });

        jLabel7.setText("Forma de pagamento:");

        jLabel9.setText("Valor final:");

        txtAreaComandas.setColumns(20);
        txtAreaComandas.setRows(5);
        jScrollPane1.setViewportView(txtAreaComandas);

        FecharComanda.setText("Fechar comanda");
        FecharComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharComandaActionPerformed(evt);
            }
        });

        FecharMenu.setText("Fechar Menu");
        FecharMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharMenuActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo(2).png"))); // NOI18N

        jLabel1.setText("ID da comanda para edição:");

        txtIdComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdComandaActionPerformed(evt);
            }
        });

        FPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AbrirComanda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoverComanda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ListarComandas)
                                .addGap(13, 13, 13)
                                .addComponent(EditarComanda))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCliente)))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGarcom)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FecharComanda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FecharMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdComanda)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIdGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbrirComanda)
                    .addComponent(EditarComanda)
                    .addComponent(ListarComandas)
                    .addComponent(RemoverComanda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FecharComanda)
                            .addComponent(FecharMenu)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirComandaActionPerformed
        try {
            ComandasBO bo = new ComandasBO();
            Comandas comanda = new Comandas();

            String nomeCliente = txtCliente.getText();
            String nomeGarcom = txtGarcom.getText();
            int idGarcom = Integer.parseInt(txtIdGarcom.getText());
            int mesa = Integer.parseInt(txtMesa.getText());

            comanda.setNomePessoa(nomeCliente);
            comanda.setNomeGarcom(nomeGarcom);
            comanda.setIdGarcom(idGarcom);
            comanda.setMesa(mesa);
            comanda.setStatus(true);
            comanda.setDataAbertura(LocalDateTime.now());

            bo.abrirComanda(comanda);
            atualizarListagemComandas();
            JOptionPane.showMessageDialog(this, "Comanda aberta com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir comanda: " + e.getMessage());
        }
    }//GEN-LAST:event_AbrirComandaActionPerformed

    private void ListarComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarComandasActionPerformed
        atualizarListagemComandas();
    }//GEN-LAST:event_ListarComandasActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesaActionPerformed

    private void txtIdGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdGarcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdGarcomActionPerformed

    private void FecharComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharComandaActionPerformed
        try {
            ComandasBO bo = new ComandasBO();

            int idComanda = Integer.parseInt(txtIdComanda.getText());
            float valorFinal = Float.parseFloat(txtValor.getText());
            String formaPagamento = FPagamento.getSelectedItem().toString();

            Comandas comanda = bo.buscarComandaPorId(idComanda);
            if (comanda == null) {
                JOptionPane.showMessageDialog(this, "Comanda não encontrada!");
                return;
            }
            if (!comanda.isStatus()) {
                JOptionPane.showMessageDialog(this, "Comanda já está fechada!");
                return;
            }

            bo.fecharComanda(idComanda, valorFinal, formaPagamento);
            atualizarListagemComandas();
            JOptionPane.showMessageDialog(this, "Comanda fechada com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao fechar comanda: " + e.getMessage());
        }
    }//GEN-LAST:event_FecharComandaActionPerformed

    private void EditarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarComandaActionPerformed
        try {
            int id = Integer.parseInt(txtIdComanda.getText());
            ComandasBO bo = new ComandasBO();
            Comandas comanda = bo.buscarComandaPorId(id);
            if (comanda == null || !comanda.isStatus()) {
                JOptionPane.showMessageDialog(this, "Comanda não encontrada ou já fechada!");
                return;
            }

            comanda.setMesa(Integer.parseInt(txtMesa.getText()));
            comanda.setNomePessoa(txtCliente.getText());
            comanda.setIdGarcom(Integer.parseInt(txtIdGarcom.getText()));
            comanda.setNomeGarcom(txtGarcom.getText());

            bo.editarComanda(comanda);
            atualizarListagemComandas();
            JOptionPane.showMessageDialog(this, "Comanda editada com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao editar comanda: " + e.getMessage());
        }
    }//GEN-LAST:event_EditarComandaActionPerformed

    private void RemoverComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverComandaActionPerformed
        try {
            ComandasBO bo = new ComandasBO();
            int idComanda = Integer.parseInt(txtIdComanda.getText());
            bo.excluirComanda(idComanda);
            atualizarListagemComandas();
            JOptionPane.showMessageDialog(this, "Comanda removida com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao remover comanda: " + e.getMessage());
        }
    }//GEN-LAST:event_RemoverComandaActionPerformed

    private void FecharMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharMenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharMenuActionPerformed

    private void txtIdComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdComandaActionPerformed

    private void FPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPagamentoActionPerformed
        JComboBox<String> cbFormaPagamento = new JComboBox<>();
        cbFormaPagamento.addItem("Dinheiro");
        cbFormaPagamento.addItem("Cartão");
        cbFormaPagamento.addItem("Pix");
    }//GEN-LAST:event_FPagamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirComanda;
    private javax.swing.JButton EditarComanda;
    private javax.swing.JComboBox<String> FPagamento;
    private javax.swing.JButton FecharComanda;
    private javax.swing.JButton FecharMenu;
    private javax.swing.JButton ListarComandas;
    private javax.swing.JButton RemoverComanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaComandas;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtGarcom;
    private javax.swing.JTextField txtIdComanda;
    private javax.swing.JTextField txtIdGarcom;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    
}
