/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package App;
import BO.ComandasBO;
import BO.PedidosBO;
import DAO.ComandasDAO;
import Model.Comandas;
import Model.Pedidos;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class FecharComanda extends javax.swing.JDialog {
    private ComandasBO comandasBO = new ComandasBO(); 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FecharComanda.class.getName());

    /**
     * Creates new form FecharComanda
     */
    public FecharComanda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private int idComandaP;
    public void carregarTabelaPedidos(int idComandaP){
        PedidosBO pbo = new PedidosBO();
        List<Pedidos> listaPedidosComanda = pbo.listarPedidos(idComandaP);
        DefaultTableModel model = (DefaultTableModel) tabelaPedidos.getModel();
        model.setRowCount(0);
        for (Pedidos pedido : listaPedidosComanda){
            Object[] novaLinha = {pedido.getId(), pedido.getNomeProduto(), pedido.getQtd(), pedido.getPrecoProduto(), (pedido.getPrecoProduto()*pedido.getQtd())};
            model.addRow(novaLinha);
        }
    }
    public void recarregarTabelaPedidos() {
        carregarTabelaPedidos(idComandaP);
        tabelaPedidos.revalidate();
        tabelaPedidos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idComanda = new javax.swing.JTextField();
        FecharComanda = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        Simular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CaixaPreco = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID da comanda:");

        idComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComandaActionPerformed(evt);
            }
        });

        FecharComanda.setText("Fechar comanda");
        FecharComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharComandaActionPerformed(evt);
            }
        });

        Fechar.setText("Cancelar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });

        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Qtd", "Preço Unit.", "Preço final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaPedidos.setToolTipText("");
        jScrollPane1.setViewportView(tabelaPedidos);

        Simular.setText("Simular");
        Simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimularActionPerformed(evt);
            }
        });

        jLabel2.setText("Preço final:");

        CaixaPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FecharComanda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Simular)
                        .addGap(43, 43, 43)
                        .addComponent(Fechar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CaixaPreco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idComanda)))
                        .addGap(89, 89, 89)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CaixaPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FecharComanda)
                    .addComponent(Simular))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idComandaActionPerformed
    private boolean resetTabela;
    public boolean testarExecucao(){
        return resetTabela;
    }
    private void FecharComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharComandaActionPerformed
        int idFechar = Integer.parseInt(idComanda.getText()); 
        boolean resposta = true;

        Comandas comandaParaFechar = null;
        
        List<Comandas> lc = comandasBO.listarAbertas();
        for(Comandas comanda : lc){
            if(idFechar == comanda.getId()){
                comandaParaFechar = comanda;
            }  
        }
        
        if (comandaParaFechar == null) {
            JOptionPane.showMessageDialog(this, "Comanda não encontrada!");
            return;
        }

        PedidosBO pedBO = new PedidosBO();
        comandaParaFechar.setListaPedidos(pedBO.listarPedidos(idFechar));


        float totalPedidos = 0;
        for (Pedidos p : comandaParaFechar.getListaPedidos()) {
            totalPedidos += p.getPrecoProduto() * p.getQtd();
        }

        float precoFinal = totalPedidos;
        

        comandaParaFechar.setPrecoFinal(precoFinal);

        ComandasDAO cdao = new ComandasDAO();
        cdao.fecharComanda(comandaParaFechar); 

        comandasBO.listarAbertas();
        comandasBO.listarFechadas();
        
        JOptionPane.showMessageDialog(this, 
            "Comanda fechada com sucesso");

        resetTabela = true;

        this.dispose();

    }//GEN-LAST:event_FecharComandaActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharActionPerformed

    private void SimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimularActionPerformed
        int idFechar = Integer.parseInt(idComanda.getText()); 
        boolean resposta = true;
        
        carregarTabelaPedidos(idFechar);
        Comandas comandaParaFechar = null;
        
        List<Comandas> lc = comandasBO.listarAbertas();
        for(Comandas comanda : lc){
            if(idFechar == comanda.getId()){
                comandaParaFechar = comanda;
            }  
        }
        
        if (comandaParaFechar == null) {
            JOptionPane.showMessageDialog(this, "Comanda não encontrada!");
            return;
        }

        PedidosBO pedBO = new PedidosBO();
        comandaParaFechar.setListaPedidos(pedBO.listarPedidos(idFechar));


        float totalPedidos = 0;
        for (Pedidos p : comandaParaFechar.getListaPedidos()) {
            totalPedidos += p.getPrecoProduto() * p.getQtd();
        }

        float precoFinal = totalPedidos;
        float valorFinal = precoFinal;
        CaixaPreco.setText(String.format("%.2f", valorFinal));
        
    }//GEN-LAST:event_SimularActionPerformed

    private void CaixaPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaPrecoActionPerformed

    }//GEN-LAST:event_CaixaPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FecharComanda dialog = new FecharComanda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaixaPreco;
    private javax.swing.JButton Fechar;
    private javax.swing.JButton FecharComanda;
    private javax.swing.JButton Simular;
    private javax.swing.JTextField idComanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabelaPedidos;
    // End of variables declaration//GEN-END:variables
}
